-- Tables
SELECT * FROM RESORTS;
SELECT * FROM HOTELS;
SELECT * FROM ROOMS;
SELECT * FROM GUESTS;
SELECT * FROM BOOKINGS;

-- R1
SELECT
    NS, NOMS, CAPCH
FROM
    RESORTS
WHERE
    TYPES = 'montagne';

-- R2
SELECT
    NOMH, NH, ADRH, TELH, CATH
FROM
    HOTELS H, RESORTS R
WHERE
    H.NS = R.NS
    AND TYPES = 'mer';

-- R3
SELECT
    DISTINCT NOMS
FROM
    RESORTS R, HOTELS H
WHERE
    R.NS = H.NS
    AND TYPES = 'mer'
    AND CATH = 4;

-- R4
SELECT
    DISTINCT NOMCL, ADRCL
FROM
    GUESTS G, BOOKINGS B, RESORTS R
WHERE
    G.NCL = B.NCL
    AND B.NS = R.NS
    AND TYPES = 'montagne';

-- R5
SELECT
    NCH, H.NH
FROM
    ROOMS RM, HOTELS H, RESORTS R
WHERE
    RM.NH = H.NH
    AND RM.NS = R.NS
    AND H.NS = R.NS
    AND CATH = 2
    AND TYPES = 'montagne'
    AND PRIX < 50;

-- R6
SELECT
    DISTINCT NOMCL
FROM
    GUESTS G, RESORTS R, HOTELS H, ROOMS RM, BOOKINGS B
WHERE
    G.NCL = B.NCL
    AND B.NS = R.NS
    AND B.NH = H.NH
    AND H.NS = R.NS
    AND B.NCH = RM.NCH
    AND RM.NS = R.NS
    AND RM.NH = H.NH
    AND TYPES = 'mer'
    AND TYPCH LIKE 'D%';

-- R7
SELECT
    DISTINCT NOMCL
FROM
    GUESTS G, HOTELS H, BOOKINGS B
WHERE
    G.NCL = B.NCL
    AND B.NH = H.NH
    AND ADRCL = ADRH;

-- R8
SELECT
    NS, NH
FROM
    HOTELS
WHERE
    CATH = 4 MINUS
    SELECT
        NS, NH
    FROM
        ROOMS
    WHERE
        TYPCH <> 'SDB';