-- Tables
SELECT * FROM JOUEURS;
SELECT * FROM RENCONTRES;
SELECT * FROM GAINS;
SELECT * FROM SPONSORS;

-- R1
SELECT
    J.NJ, PRIME
FROM
    JOUEURS J, GAINS G
WHERE
    J.NJ = G.NJ
    AND G.NOMSPONSOR = 'PEUGEOT'
    AND G.ANNEE BETWEEN 2003 AND 2005;

-- R2
SELECT
    DISTINCT NOM, AGE
FROM
    JOUEURS J, RENCONTRES R
WHERE
    (J.NJ = R.NJGAGNANT
    OR J.NJ = R.NJPERDANT)
    AND R.LIEUTOURNOI = 'Roland Garros'
    AND R.ANNEE = 2005;

-- R3
SELECT
    DISTINCT NOM, NATIONALITE
FROM
    JOUEURS J, RENCONTRES R, GAINS G
WHERE
    J.NJ = R.NJGAGNANT
    AND J.NJ = G.NJ
    AND G.NOMSPONSOR = 'PEUGEOT'
    AND R.LIEUTOURNOI = 'Roland Garros';

-- R4
SELECT
    DISTINCT NOM, NATIONALITE
FROM
    JOUEURS J, RENCONTRES R
WHERE
    (J.NJ = R.NJGAGNANT
    OR J.NJ = R.NJPERDANT)
    AND R.LIEUTOURNOI = 'Roland Garros'
    AND R.ANNEE = 2006 INTERSECT
    SELECT
        DISTINCT NOM, NATIONALITE
    FROM
        JOUEURS J, RENCONTRES R
    WHERE
        (J.NJ = R.NJGAGNANT
        OR J.NJ = R.NJPERDANT)
        AND R.LIEUTOURNOI = 'Wimbledon'
        AND R.ANNEE = 2006;

-- R5
SELECT
    DISTINCT NOM
FROM
    JOUEURS J, GAINS G
WHERE
    J.NJ = G.NJ
    AND G.LIEUTOURNOI = 'Roland Garros'
    AND G.PRIME >= 150000 MINUS
    SELECT
        DISTINCT NOM
    FROM
        JOUEURS J, GAINS G
    WHERE
        J.NJ = G.NJ
        AND G.LIEUTOURNOI = 'Roland Garros'
        AND G.PRIME < 150000;
